import { describe, it } from "vitest";

import { chess } from "../harness.js";

describe("Risky Chess, 2026-04-18", () => {
  it("plays through the full game", () => {
    chess("risky")
      .play("d4", "Nc6")
      .play("c3", "e5")
      .play("Nf3", "d6")
      .play("e3", "Bf5")
      .play("Nh4", "Bxb1")
      .play("Rxb1", "Qxh4")
      .play("g3", "Qh6")
      .play("Bb5", "g6")
      .play("Qg4", "f5")
      .play("Qf3", "e4")
      .play("Qe2", "O-O-O")
      .play("Qc4", "Nge7")
      .play("Qe6", "Kb8")
      .play("Qf6", "g5")
      .play("Qxh8", "f4")
      .play("gxf4", "gxf4")
      .play("exf4", "Ng6")
      .play("Qf6", "a6")
      .play("Bc4", "Nxf4")
      .play("Qf7", "Nd3")
      .play("O-O", "e3")
      .play("Bxe3", "Qg6")
      .play("Qxg6", "hxg6")
      .play("Bxd3", "Ne7")
      .play("b4", "Bg7")
      .play("Bf4", "Rg8")
      .play("Rfe1", "Bf6")
      .play("Re6", "g5")
      .play("Rxf6", "gxf4")
      .play("Kf1", "Nd5")
      .play("Re6", "f3")
      .play("Rbe1", "Nf4")
      .play("Re8", "Rxe8")
      .play("Rxe8", "Ka7")
      .play("Be4", "b6")
      .play("Re7", "a5")
      .play("Rxc7", "Ka6")
      .play("Bb7", "Kb5")
      .play("Bxf3", "axb4")
      .play("Bc6", "Kc4")
      .play("Ba4", "Kd3")
      .play("cxb4", "Kxd4")
      .play("Bb3", "d5")
      .play("a4", "Nd3")
      .play("Rd7", "Nxb4")
      .play("h4", "Kc5")
      .play("h5", "Kc6")
      .play("Rg7", "d4")
      .play("h6", "d3")
      .play("h7", "d2")
      .play("h8=Q", "b5")
      .play("Qa8", "Kc5")
      .play("Qc8", "Kd4")
      .play("Rg4", "Kd3")
      .play("Rxb4", "d1=Q")
      .play("Bxd1", "Kd2")
      .play("Qd8", "Kc3")
      .play("Rxb5", "Kc4")
      .play("Rg5", "Kb4")
      .play("a5", "Kc3")
      .play("Rc5", "Kb2")
      .play("Qb6", "Ka3")
      .play("Qb3", "Kxb3")
      .play("Bxb3#")
      .assertGameOver("white", "king captured — 22 points ahead");
  });
});
